apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: super-namespace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-namespace-controller
  template:
    metadata:
      labels:
        app: super-namespace-controller
    spec:
      containers:
      - name: controller
        image: python:2.7
        command: ["python", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: super-namespace-controller
---
apiVersion: v1
kind: Service
metadata:
  name: super-namespace-controller
spec:
  selector:
    app: super-namespace-controller
  ports:
  - port: 80